# Number of instances to create
instance_count: 2

# Version of the microk8s snap to use
microk8s_version: "1.25/stable"

# Prefix of the nodes in Openstack
nodes_name: "k8s-host"

# The name of the image in OpenStack to use
nodes_image: "Ubuntu 20.04"

# The flavor in OpenStack to use
nodes_flavor_name: "Compute G3 - x4"

# The name of the security group in OpenStack
security_group: "default"

# The name of the key to use in OpenStack
key_name: "dev"

# The domain name for OpenStack to use
domain_name: "sharcnet"

# The ID of the project in OpenStack to deploy the machines in
project_id: "63e63b6f8f0843749621ff85f2a29f42"

# The name of the network to attach the VM to
network_name: "DIVERT Mental Health: Private Network"

# Prefix and suffix for the created kubeconf files
generated_kubeconf_file_prefix: "{{ playbook_dir + '/generated-' }}"
generated_kubeconf_file_suffix: "-kube.conf"

# Should the generated VM allow for password-based login
enable_password_login_for_user_ubuntu: false
password_for_user_ubuntu: "changeme{{ 100 | random(seed=playbook_dir) }}"

# The folder to generate the terraform files in
terraform_folder: "{{ playbook_dir }}/generated-terraform/"

# The SSH known hosts file to modify
ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
