terraform_folder: "{{ playbook_dir }}/generated-terraform/"

enable_password_login_for_user_ubuntu: false
password_for_user_ubuntu: "changeme{{ 100 | random(seed=playbook_dir }}"

instance_count: 25
microk8s_version: "1.25/stable"

nodes_name: "microk8s-host"
nodes_image: "Ubuntu Server 20.04 64bit"
nodes_flavor_name: "m1.large"
security_group: "default"
key_name: "Dennis 2017"
domain_name: "default"
project_id: "124048b2da0c44e5aee6eca2d180de30"
network_name: "DHBW"

generated_kubeconf_file_prefix: "{{ playbook_dir + '/generated-' }}"
generated_kubeconf_file_suffix: "-kube.conf"

ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
