---
# ----------------------------------------------------
# Enable code completion
# ----------------------------------------------------

- name: Enable shell completion
  shell: kubectl completion bash > /etc/bash_completion.d/kubectl
  args:
    creates: /etc/bash_completion.d/kubectl

# ----------------------------------------------------
# Install helm
# ----------------------------------------------------

#- name: Install helm APT repo key
#  apt_key:
#    url: "https://helm.baltorepo.com/organization/signing.asc"
#    state: present

#- name: Setup helm APT repo
#  apt_repository:
#    repo: deb https://baltocdn.com/helm/stable/debian/ all main
#    state: present

#- name: Install Helm
#  apt:
#    name: ["helm"]
#    state: present
#    update_cache: yes

- name: Install helm
  shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
