#!ansible-playbook
---
# ----------------------------------------------------
- name: Create cloud resources (and wait for them to be ready)
  hosts: localhost
  gather_facts: false
  roles:
    - role: terraform
  tags: ["terraform", "cloud"]
  post_tasks:
    - name: Remove existing SSH key entries for the cloud instances machine
      shell: "ssh-keygen -R {{ hostvars[item]['ansible_ssh_host'] }}"
      ignore_errors: True
      changed_when: False
      with_items: "{{ groups.all }}"

# ----------------------------------------------------
#- name: Wait for nodes to be ready (port available)
#  hosts: localhost
#  tasks:
#    - name: Wait during nodes boot (port available)
#      wait_for:
#        port: 22
#       search_regex: OpenSSH
#        host: "{{ hostvars[item]['ansible_ssh_host'] }}"
#        timeout: 180
#      with_items: "{{ groups.all }}"
#  ignore_errors: True

- name: Wait during nodes boot (ssh available)
  hosts: all
  gather_facts: false
  user: ubuntu
  tasks:
    - name: Wait during nodes boot (ssh available)
      wait_for_connection:
        timeout: 60

# ----------------------------------------------------
- name: Manage SSH known_hosts file on local host
  hosts: localhost
  connection: local
  roles:
    - role: ssh-keys
  tags: ["ssh"]

# ----------------------------------------------------
- name: Wait for nodes to finish cloud init
  hosts: all
  gather_facts: False
  user: ubuntu
  tags: ["cloud"]
  roles:
    - role: wait-cloud-init-done

- name: Delete resources for failed hosts
  hosts: localhost
  roles:
    - role: delete-failed-terraform
      vars: { "required_key": "cloud_init_success" }

#-------------------------------------------------------
- name: Configure password-based login for user ubuntu
  hosts: all
  user: ubuntu
  become: True
  become_user: root
  roles:
    - role: allow-password

- name: Delete resources for failed hosts
  hosts: localhost
  roles:
    - role: delete-failed-terraform
      vars: { "required_key": "allow_password_success" }

# ----------------------------------------------------
- name: Install microk8s
  hosts: all
  user: ubuntu
  become: True
  become_user: root
  roles:
    - role: microk8s

- name: Delete resources for failed hosts
  hosts: localhost
  roles:
    - role: delete-failed-terraform
      vars: { "required_key": "microk8s_success" }

# ----------------------------------------------------
- name: Fix permissions of kubeconf file(s)
  hosts: localhost
  connection: local
  tasks:
    - name: Change permissions
      ansible.builtin.file:
        path: "{{item}}"
        mode: "0600"
      with_fileglob:
        - "{{generated_kubeconf_file_prefix}}*{{ generated_kubeconf_file_suffix }}"
