---
# ----------------------------------------------------
# Create OpenStack resources cluster and wait for cloud init to finish
# ----------------------------------------------------
- name: Create OpenStack resources cluster
  hosts: localhost
  gather_facts: false
  roles:
    - role: openstack

- name: Wait for nodes to be ready
  hosts: all
  gather_facts: False
  tags:
    - openstack
  tasks:
    - name: Wait during nodes boot
      wait_for:
        host: "{{ansible_ssh_host}}"
        port: 22
        connect_timeout: 20
        timeout: 600
        search_regex: OpenSSH
      vars:
        ansible_connection: local

# ----------------------------------------------------
# Scan SSH keys
# ----------------------------------------------------

- name: SSH keys
  hosts: localhost
  connection: local
  tags:
    - openstack
  roles:
    - role: ssh-keys

# ----------------------------------------------------
# Wait for nodes to be ready
# ----------------------------------------------------

- name: Wait for nodes to be ready
  hosts: all
  gather_facts: False
  tags:
    - openstack
  tasks:
    - name: Wait for cloud-init to finish
      raw: while ! test -f /var/lib/cloud/instance/boot-finished; do sleep 1; done
      retries: 5
      delay: 1
      changed_when: False
      tags:
        - skip_ansible_lint

# ----------------------------------------------------
# Install microk8s
# ----------------------------------------------------

- name: Install microk8s
  hosts: all
  user: ubuntu
  become: yes
  become_user: root
  gather_facts: false
  tags:
    - base
  roles:
    - role: microk8s

# ----------------------------------------------------
# Install addons
# ----------------------------------------------------

- name: Install addons
  hosts: localhost
  connection: local
  gather_facts: false
  environment:
    KUBECONFIG: "{{generated_kubeconf_file}}"
  roles:
    - role: microk8s-addons
