- name: Delete failed hosts
  debug:
      msg: "Deleting host {{ item }} with index {{ idx }} (key={{ required_key }})"
  when: required_key not in hostvars[item]
  loop: "{{ hostvars.keys() }}"
  loop_control:
      index_var: idx

- name: Delete failed hosts
  terraform:
      force_init: yes
      project_path: "{{ terraform_folder }}"
      state: "absent" # present / planned / absent
      targets: "openstack_compute_instance_v2.openstack_instances[{{ idx }}]"
  when: required_key not in hostvars[item]
  loop: "{{ hostvars.keys() }}"
  loop_control:
      index_var: idx

- name: Delete kubeconfig files locally
  debug:
      msg: "{{ local_kubeconf_file_name }}"
  delegate_to: localhost
  when: required_key not in hostvars[item]
  loop: "{{ hostvars.keys() }}"
  loop_control:
      index_var: idx

- name: Delete kubeconfig files locally
  ansible.builtin.file:
      path: local_kubeconf_file_name
      state: absent
  delegate_to: localhost
  when: required_key not in hostvars[item]
  loop: "{{ hostvars.keys() }}"
  loop_control:
      index_var: idx
